token = "b04d5cdebd8cfd2b130a75aa51889f3d9e574458465b92d7696cff3d32a0eec5fe880235aec313f893379" # –¢–æ–∫–µ–Ω —Å–æ–æ–±—â–µ—Å—Ç–≤–∞ –í–ö–æ–Ω—Ç–∞–∫—Ç–µ
buttons_text = "–°–ü–ê–ú"
message_text = "–ö–∏—Ä–∏–ª–ª –ª–æ—Ö, –∫—Ä—ã—Å–∞, –ø–∏–¥–∞—Ä–∞—Å @online ü§ü " # –¢–µ–∫—Å—Ç —Å–æ–æ–±—â–µ–Ω–∏—è. –ï—Å–ª–∏ –∫–æ—Ä–æ—á–µ 4096 –±–∞–π—Ç–æ–≤ - –±—É–¥–µ—Ç –ø–æ–≤—Ç–æ—Ä—ë–Ω –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–∞–∑
logging_level = "DEBUG"
delay = 0.33
