token = "b04d5cdebd8cfd2b130a75aa51889f3d9e574458465b92d7696cff3d32a0eec5fe880235aec313f893379" # Токен сообщества ВКонтакте

buttons_text = "СПАМ"
message_text = " АОАОАОАОАООАОАОАО " # Текст сообщения. Если короче 4096 байтов - будет повторён максимальное количество раз

logging_level = "DEBUG"
delay = 0.11
